# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Flow": "core.ipynb",
         "identity": "utils.ipynb",
         "simplify": "utils.ipynb",
         "listify": "utils.ipynb",
         "setify": "utils.ipynb",
         "tuplify": "utils.ipynb",
         "merge_tfms": "utils.ipynb",
         "compose": "utils.ipynb",
         "pipe": "utils.ipynb",
         "get_files": "utils.ipynb",
         "function": "utils.ipynb",
         "T": "utils.ipynb"}

modules = ["core.py",
           "utils.py"]

doc_url = "//"

git_url = "https://github.com/limiteinductive/LazyFlow"

def custom_doc_links(name): return None
