# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Flow": "core.ipynb",
         "identity": "utils.ipynb",
         "T": "utils.ipynb"}

modules = ["core.py",
           "utils.py"]

doc_url = "//"

git_url = "https://github.com/limiteinductive/LazyFlow"

def custom_doc_links(name): return None
