# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/core.ipynb (unless otherwise specified).

__all__ = ['Flow']

# Cell
from returns.pipeline import flow
from returns.maybe import Maybe

#from ..lazyflow.utils import identity

class Flow:

    def __init__(self, input=Maybe, functions=Maybe, outputs=Maybe):
        self.input = input
        self.functions = functions
        self.output = outputs


    def __call__(self, input=None):

        if input:
            return flow(input, self.functions)

        self.outputs = flow(self.input, self.functions)

        return self.outputs



