# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/core.ipynb (unless otherwise specified).

__all__ = ['Flow']

# Cell
from returns.pipeline import flow
from returns.maybe import Maybe

from .utils import identity

class Flow:

    def __init__(self, input=Maybe, functions=identity, outputs=Maybe):
        self.input = input
        self.functions = listify(functions)
        self.outputs = outputs


    def __call__(self, input=None):

        if input:
            return flow(input, self.functions)

        self.outputs = flow(self.input, self.functions)
        return self.outputs

    def __rshift__(self, flow):

        if self.outputs:
            i = self.outputs
        else:
            i = self()

        return Flow(self.input, self.functions+flow.functions, flow.functions(i))



