# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utils.ipynb (unless otherwise specified).

__all__ = ['identity', 'T']

# Cell
from typing import TypeVar

T = TypeVar("T")

def identity(x: T) -> T: return x